#!/bin/sh
# SPDX-FileCopyrightText: 2026 IMPCAS
#
# SPDX-License-Identifier: MIT

# Configure networking and time sync from /boot/machine.cfg (a plain KEY=value
# file on the writable BOOT partition, edited per machine before first boot).
# The rootfs is read-only and identical on every machine, so the generated
# network configuration goes to /run, which systemd-networkd and
# systemd-timesyncd read like any other configuration directory.
#
# Keys:
#   INTERFACE   interface name to match (default eth0)
#   MACADDRESS  hardware address to set on the interface
#   IPADDRESS   static IPv4 address
#   NETMASK     dotted netmask (or use PREFIXLEN directly)
#   PREFIXLEN   prefix length, takes precedence over NETMASK
#   GATEWAY     default gateway
#   DNS         space-separated DNS servers
#   NTP         space-separated NTP servers
#   HOSTNAME    machine host name (written to /etc/hostname and applied)
#
# Time sync daemon selection, highest priority first: chronyd > ntpd >
# systemd-timesyncd. The base image ships only systemd-timesyncd; if another
# variant also installs ntpd or chronyd, that daemon takes over. The NTP=
# server list is written for every installed daemon (chronyd and ntpd via
# their /etc config files, timesyncd via a /run drop-in and the networkd
# NTP= link lines), but only the highest-priority daemon is left enabled so
# that two of them never adjust the clock at once.
#
# With no /boot/machine.cfg the service exits and the built-in networkd
# configuration applies unchanged.

set -e

CFG=/boot/machine.cfg
NETWORK_DIR=/run/systemd/network
TIMESYNC_CONF=/run/systemd/timesyncd.conf.d/bootcfg.conf
NETWORK_FILE=$NETWORK_DIR/80-bootcfg.network
HOSTNAME_FILE=/etc/hostname
NTPD_CONF=/etc/ntp.conf
CHRONYD_CONF=/etc/chrony/chrony.conf
TIME_UNITS="chronyd.service ntpd.service systemd-timesyncd.service"

[ -r "$CFG" ] || { echo "bootcfg: no $CFG, keeping built-in network config"; exit 0; }

# Only plain KEY=value lines with a safe value charset are accepted; the file
# is sourced, so anything that could execute must be rejected up front.
if grep -Evq '^[[:space:]]*(#|$)|^[A-Za-z_][A-Za-z0-9_]*="?[A-Za-z0-9_.:/ -]*"?[[:space:]]*$' "$CFG"; then
    echo "bootcfg: $CFG contains unsupported lines, ignoring it" >&2
    exit 1
fi

. "$CFG"

INTERFACE=${INTERFACE:-eth0}

# NETMASK (e.g. 255.255.255.0) -> prefix length, plain POSIX arithmetic.
mask_to_prefix() {
    prefix=0
    for octet in $(echo "$1" | tr '.' ' '); do
        while [ "$octet" -ne 0 ]; do
            prefix=$((prefix + octet % 2))
            octet=$((octet / 2))
        done
    done
    echo "$prefix"
}

if [ -z "$PREFIXLEN" ] && [ -n "$NETMASK" ]; then
    PREFIXLEN=$(mask_to_prefix "$NETMASK")
fi

mkdir -p "$NETWORK_DIR"

{
    echo "[Match]"
    echo "Name=$INTERFACE"
    echo ""
    echo "[Link]"
    [ -n "$MACADDRESS" ] && echo "MACAddress=$MACADDRESS"
    echo ""
    echo "[Network]"
    if [ -n "$IPADDRESS" ]; then
        if [ -n "$PREFIXLEN" ]; then
            echo "Address=$IPADDRESS/$PREFIXLEN"
        else
            echo "Address=$IPADDRESS"
        fi
    fi
    [ -n "$GATEWAY" ] && echo "Gateway=$GATEWAY"
    for server in $DNS; do
        echo "DNS=$server"
    done
    for server in $NTP; do
        echo "NTP=$server"
    done
} > "$NETWORK_FILE"

# A daemon counts as installed if its unit file exists anywhere on the unit
# search path, regardless of enablement: arbitration must also work for a
# daemon the image ships but nobody enabled yet.
unit_installed() {
    [ -e "/usr/lib/systemd/system/$1" ] ||
    [ -e "/etc/systemd/system/$1" ] ||
    [ -e "/run/systemd/system/$1" ]
}

write_timesyncd_conf() {
    mkdir -p "$(dirname "$TIMESYNC_CONF")"
    {
        echo "[Time]"
        echo "NTP=$NTP"
        # Windows w32time sources report root dispersion in the seconds
        # range (it grows over their long poll interval), which trips the
        # 5s default and makes timesyncd reject a server that is actually
        # stratum-3 synced. Site LAN sources, so allow more slack.
        echo "RootDistanceMaxSec=15"
    } > "$TIMESYNC_CONF"
}

write_ntpd_conf() {
    {
        echo "# Generated by bootcfg from $CFG; edit machine.cfg, not this file."
        echo "driftfile /var/lib/ntp/ntp.drift"
        echo "tinker panic 0"
        echo "restrict -4 default kod notrap nomodify nopeer noquery limited"
        echo "restrict -6 default kod notrap nomodify nopeer noquery limited"
        echo "restrict source"
        for server in $NTP; do
            echo "server $server iburst"
        done
    } > "$NTPD_CONF"
}

write_chronyd_conf() {
    {
        echo "# Generated by bootcfg from $CFG; edit machine.cfg, not this file."
        echo "driftfile /var/lib/chrony/drift"
        echo "makestep 1.0 3"
        echo "rtcsync"
        for server in $NTP; do
            echo "server $server iburst"
        done
    } > "$CHRONYD_CONF"
}

ACTIVE=""
for unit in $TIME_UNITS; do
    if unit_installed "$unit"; then
        ACTIVE=$unit
        break
    fi
done

TIME_CFG=""
if [ -n "$ACTIVE" ] && [ -n "$NTP" ]; then
    for unit in $TIME_UNITS; do
        unit_installed "$unit" || continue
        case $unit in
            chronyd.service)
                write_chronyd_conf
                [ "$unit" = "$ACTIVE" ] && TIME_CFG=$CHRONYD_CONF
                ;;
            ntpd.service)
                write_ntpd_conf
                [ "$unit" = "$ACTIVE" ] && TIME_CFG=$NTPD_CONF
                ;;
            systemd-timesyncd.service)
                write_timesyncd_conf
                [ "$unit" = "$ACTIVE" ] && TIME_CFG=$TIMESYNC_CONF
                ;;
        esac
        [ "$unit" = "$ACTIVE" ] && continue
        # Keep the non-active daemons correctly configured but inactive; they
        # can be switched on later without touching machine.cfg.
        systemctl disable --now "$unit" 2>/dev/null || true
    done
    # bootcfg is not ordered against the time daemons (systemd-timesyncd is a
    # sysinit-phase unit and a Before= edge from this multi-user service would
    # close an ordering cycle -- see bootcfg.service), so the active daemon may
    # already be running with a stale configuration -- or may have exited at
    # sysinit for lack of servers. restart (unlike try-restart) also starts a
    # dead unit, so the freshly written configuration always applies.
    systemctl restart "$ACTIVE" 2>/dev/null || true
elif [ -n "$ACTIVE" ]; then
    # No NTP key: still enforce one-daemon-only, but write no configuration.
    for unit in $TIME_UNITS; do
        [ "$unit" = "$ACTIVE" ] && continue
        unit_installed "$unit" || continue
        systemctl disable --now "$unit" 2>/dev/null || true
    done
fi

if [ -n "$HOSTNAME" ]; then
    # The rootfs is mounted rw at runtime, so /etc/hostname is writable and
    # the name survives reboots without the bootcfg service.
    echo "$HOSTNAME" > "$HOSTNAME_FILE"
    hostname "$HOSTNAME"
fi

MSG="bootcfg: wrote $NETWORK_FILE"
[ -n "$TIME_CFG" ] && MSG="$MSG and $TIME_CFG for $ACTIVE"
[ -n "$HOSTNAME" ] && MSG="$MSG, hostname $HOSTNAME"
echo "$MSG from $CFG"

exit 0
